version: '3.8'

services:
  backend:
    build: ./server
    expose:
      - "8000"
  
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для работы Hot Reload в Docker
    volumes:
      - ./client/src:/app/src
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
